# Generated by Django 4.2 on 2025-01-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_docentes_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cursos'),
        ),
    ]
